import os
import shutil


def _write_xml_file(file_path: str, content: str):
    """Escribe un archivo XML con codificación UTF-8, creando directorios si es necesario."""
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)


def create_minimal_theme(theme_folder: str, assets_folder_name: str = "assets"):
    """
    Crea la estructura base de un theme en theme_folder:
    - theme.xml con includes y subsets comunes
    - Subcarpetas para subsets, vistas, assets
    - Archivos XML mínimos para cada include referenciado
    """
    # Crear carpeta raíz y de assets
    os.makedirs(theme_folder, exist_ok=True)
    assets_path = os.path.join(theme_folder, assets_folder_name)
    os.makedirs(assets_path, exist_ok=True)

    # -----------------------------------------------------------------
    # 1. theme.xml principal
    # -----------------------------------------------------------------
    theme_xml = ('<?xml version="1.0" encoding="UTF-8"?>'
                 '\n\n<theme>'
                 '\n\t<formatVersion>7</formatVersion>'
                 '\n\n\t<variables>'
                 '\n\t</variables>'
                 '\n\n\t<!-- Opciones de colores  -->'
                 '\n\n\t<subset name="colorset" displayName="${subset.colorset}">'
                 '\n\t\t<include name="blue" displayName="${blue}">./subsets/colorsets/blue.xml</include>'
                 '\n\t\t<include name="red" displayName="${red}">./subsets/colorsets/red.xml</include>'
                 '\n\t\t<include name="green" displayName="${green}">./subsets/colorsets/green.xml</include>'
                 '\n\t\t<include name="cyan"  displayName="${cyan}">./subsets/colorsets/cyan.xml</include>'
                 '\n\t\t<include name="yellow" displayName="${yellow}">./subsets/colorsets/yellow.xml</include>'
                 '\n\t\t<include name="violet"  displayName="${violet}">./subsets/colorsets/violet.xml</include>'
                 '\n\t\t<include name="orange"  displayName="${orange}">./subsets/colorsets/orange.xml</include>'
                 '\n\t\t<include name="gray" displayName="${gray}">./subsets/colorsets/gray.xml</include>'
                 '\n\t</subset>'
                 '\n\n\t<!-- Vistas comunes  -->'
                 '\n\t<include>./vistas/menu.xml</include>'
                 '\n\t<include>./vistas/system.xml</include>'
                 '\n\t<include>./vistas/screen.xml</include>'
                 '\n\n\t<!-- Tipos de vistas de los juegos -->'
                 '\n\t<include>./vistas/vista_juegos/grid.xml</include>'
                 '\n\t<include>./vistas/vista_juegos/gamecarousel.xml</include>'
                 '\n\t<include>./vistas/vista_juegos/detailed.xml</include>'
                 '\n\n\t<!-- Subset tipos vistas de sistemas -->'
                 '\n\t<subset name="systemview" displayName="Vista Sistemas">'
                 '\n\t\t<include name="Wheel">./vistas/vista_sistemas/wheel.xml</include>'
                 '\n\t\t<include name="Wheel Horizontal">./vistas/vista_sistemas/wheel_horizontal.xml</include>'
                 '\n\t</subset>'
                 '\n\n\t<!-- Subset options for help -->'
                 '\n\t<subset name="helpsystem" displayName="${helpSubsetName}">'
                 '\n\t\t<include name="colored" displayName="${colored}">./subsets/help/colorhelp.xml</include>'
                 '\n\t\t<include name="standard" displayName="${gray}">./subsets/help/default.xml</include>'
                 '\n\t</subset>'
                 '\n</theme>')

    _write_xml_file(os.path.join(theme_folder, "theme.xml"), theme_xml)

    # -----------------------------------------------------------------
    # 2. Archivos XML para subsets y vistas
    files_content = {"subsets/colorsets/blue.xml": '<?xml version="1.0" encoding="UTF-8"?>'
                                                   '\n\n<theme>'
                                                   '\n\t<formatVersion>7</formatVersion>'
                                                   '\n\t<variables>'
                                                   '\n\t\t<baseColor>3675CA</baseColor>'
                                                   '\n\t\t<gradientEndColor>00205b</gradientEndColor>'
                                                   '\n\t\t<centerFadeColor>4060a050</centerFadeColor>'
                                                   '\n\t\t<bottomBarColor>4075D8C5</bottomBarColor>'
                                                   '\n\t\t<glowColor>3060Ab24</glowColor>'
                                                   '\n\t\t<systemInfoColor>FAFAFFB0</systemInfoColor>'
                                                   '\n\t\t<backgroundColor>051222</backgroundColor>'
                                                   '\n\t\t<groupColor>5178C3</groupColor>'
                                                   '\n\t\t<groupSeparatorColor>3B5B96</groupSeparatorColor>'
                                                   '\n\t</variables>'
                                                   '\n</theme>',
                     "subsets/colorsets/cyan.xml": '<?xml version="1.0" encoding="UTF-8"?>'
                                                   '\n\n<theme>'
                                                   '\n\t<formatVersion>7</formatVersion>'
                                                   '\n\t<variables>'
                                                   '\n\t\t<baseColor>1c9090</baseColor>'
                                                   '\n\t\t<gradientEndColor>105151</gradientEndColor>'
                                                   '\n\t\t<centerFadeColor>1fb3b333</centerFadeColor>'
                                                   '\n\t\t<bottomBarColor>36d2d2B0</bottomBarColor>'
                                                   '\n\t\t<glowColor>15717118</glowColor>'
                                                   '\n\t\t<systemInfoColor>FFFAFAB0</systemInfoColor>'
                                                   '\n\t\t<backgroundColor>052020</backgroundColor>'
                                                   '\n\t\t<groupColor>42C2C0</groupColor>'
                                                   '\n\t\t<groupSeparatorColor>42C2C0</groupSeparatorColor>'
                                                   '\n\t</variables>'
                                                   '\n</theme>',
                     "subsets/colorsets/gray.xml": '<?xml version="1.0" encoding="UTF-8"?>'
                                                   '\n\n<theme>'
                                                   '\n\t<formatVersion>7</formatVersion>'
                                                   '\n\t<variables>'
                                                   '\n\t\t<baseColor>A4A4A4</baseColor>'
                                                   '\n\t\t<gradientEndColor>505050</gradientEndColor>'
                                                   '\n\t\t<centerFadeColor>90909033</centerFadeColor>'
                                                   '\n\t\t<bottomBarColor>a2a2a2</bottomBarColor>'
                                                   '\n\t\t<glowColor>40404020</glowColor>'
                                                   '\n\t\t<systemInfoColor>FAFAFAB0</systemInfoColor>'
                                                   '\n\t\t<backgroundColor>121212</backgroundColor>'
                                                   '\n\t\t<groupColor>FFFFFF</groupColor>'
                                                   '\n\t\t<groupSeparatorColor>D0D0D0</groupSeparatorColor>'
                                                   '\n\t</variables>'
                                                   '\n</theme>',
                     "subsets/colorsets/green.xml": '<?xml version="1.0" encoding="UTF-8"?>'
                                                    '\n\n<theme>'
                                                    '\n\t<formatVersion>7</formatVersion>'
                                                    '\n\t<variables>'
                                                    '\n\t\t<baseColor>208b20</baseColor>'
                                                    '\n\t\t<gradientEndColor>005b00</gradientEndColor>'
                                                    '\n\t\t<centerFadeColor>208b2035</centerFadeColor>'
                                                    '\n\t\t<bottomBarColor>208b20c0</bottomBarColor>'
                                                    '\n\t\t<glowColor>105b1020</glowColor>'
                                                    '\n\t\t<backgroundColor>102510</backgroundColor>'
                                                    '\n\t\t<groupColor>46BE46</groupColor>'
                                                    '\n\t\t<groupSeparatorColor>46BE46</groupSeparatorColor>'
                                                    '\n\t</variables>'
                                                    '\n</theme>',
                     "subsets/colorsets/orange.xml": '<?xml version="1.0" encoding="UTF-8"?>'
                                                     '\n\n<theme>'
                                                     '\n\t<formatVersion>7</formatVersion>'
                                                     '\n\t<variables>'
                                                     '\n\t\t<baseColor>dd8800</baseColor>'
                                                     '\n\t\t<gradientEndColor>803F00</gradientEndColor>'
                                                     '\n\t\t<centerFadeColor>ff990033</centerFadeColor>'
                                                     '\n\t\t<bottomBarColor>ff9900B0</bottomBarColor>'
                                                     '\n\t\t<glowColor>B85F0020</glowColor>'
                                                     '\n\t\t<systemInfoColor>FFFAFAB0</systemInfoColor>'
                                                     '\n\t\t<backgroundColor>251000</backgroundColor>'
                                                     '\n\t\t<groupColor>F39F1B</groupColor>'
                                                     '\n\t\t<groupSeparatorColor>CD811B</groupSeparatorColor>'
                                                     '\n\t</variables>'
                                                     '\n</theme>',
                     "subsets/colorsets/red.xml": '<?xml version="1.0" encoding="UTF-8"?>'
                                                  '\n\n<theme>'
                                                  '\n\t<formatVersion>7</formatVersion>'
                                                  '\n\t<variables>'
                                                  '\n\t\t<baseColor>8b0000</baseColor>'
                                                  '\n\t\t<gradientEndColor>6b2020</gradientEndColor>'
                                                  '\n\t\t<centerFadeColor>8b000050</centerFadeColor>'
                                                  '\n\t\t<bottomBarColor>8b0000c0</bottomBarColor>'
                                                  '\n\t\t<glowColor>Ab000020</glowColor>'
                                                  '\n\t\t<systemInfoColor>DDDDDDD8</systemInfoColor>'
                                                  '\n\t\t<backgroundColor>200000</backgroundColor>'
                                                  '\n\t\t<groupColor>BD4747</groupColor>'
                                                  '\n\t\t<groupSeparatorColor>BD4747</groupSeparatorColor>'
                                                  '\n\t</variables>'
                                                  '\n</theme>',
                     "subsets/colorsets/yellow.xml": '<?xml version="1.0" encoding="UTF-8"?>'
                                                     '\n\n<theme>'
                                                     '\n\t<formatVersion>7</formatVersion>'
                                                     '\n\t<variables>'
                                                     '\n\t\t<baseColor>bf9f1c</baseColor>'
                                                     '\n\t\t<gradientEndColor>746111</gradientEndColor>'
                                                     '\n\t\t<centerFadeColor>d7b31f33</centerFadeColor>'
                                                     '\n\t\t<bottomBarColor>e2c036B0</bottomBarColor>'
                                                     '\n\t\t<glowColor>8B711520</glowColor>'
                                                     '\n\t\t<systemInfoColor>FAFAFFB0</systemInfoColor>'
                                                     '\n\t\t<backgroundColor>302505</backgroundColor>'
                                                     '\n\t\t<groupColor>CEB035</groupColor>'
                                                     '\n\t\t<groupSeparatorColor>CEB035</groupSeparatorColor>'
                                                     '\n\t</variables>'
                                                     '\n</theme>',
                     "subsets/colorsets/violet.xml": '<?xml version="1.0" encoding="UTF-8"?>'
                                                     '\n\n<theme>'
                                                     '\n\t<formatVersion>7</formatVersion>'
                                                     '\n\t<variables>'
                                                     '\n\t\t<baseColor>c01c8f</baseColor>'
                                                     '\n\t\t<gradientEndColor>641151</gradientEndColor>'
                                                     '\n\t\t<centerFadeColor>d71fb333</centerFadeColor>'
                                                     '\n\t\t<bottomBarColor>d236b0B0</bottomBarColor>'
                                                     '\n\t\t<glowColor>8B157118</glowColor>'
                                                     '\n\t\t<systemInfoColor>FAFFFAB0</systemInfoColor>'
                                                     '\n\t\t<backgroundColor>250515</backgroundColor>'
                                                     '\n\t\t<groupColor>D949AF</groupColor>'
                                                     '\n\t\t<groupSeparatorColor>D331A3</groupSeparatorColor>'
                                                     '\n\t</variables>'
                                                     '\n</theme>',
                     "subsets/help/colorhelp.xml": '<?xml version="1.0" encoding="UTF-8"?>'
                                                   '\n\n<theme>'
                                                   '\n\t<formatVersion>7</formatVersion>'
                                                   '\n\t<include>./default.xml</include>'
                                                   '\n\n\t<customView name="system,basic,detailed,gamecarousel,grid,Carousel,Tiles,Boxes,Icons">'
                                                   '\n\t\t<helpsystem name="help">'
                                                   '\n\t\t\t<iconColor>${baseColor}</iconColor>'
                                                   '\n\t\t\t<textColor>${baseColor}</textColor>'
                                                   '\n\t\t</helpsystem>'
                                                   '\n\t</customView>'
                                                   '\n</theme>',
                     "subsets/help/default.xml": '<?xml version="1.0" encoding="UTF-8"?>'
                                                 '\n\n<theme>'
                                                 '\n\t<formatVersion>7</formatVersion>'
                                                 '\n\n\t<customView name="system,basic,detailed,gamecarousel,grid,Carousel,Tiles,Boxes,Icons">'
                                                 '\n\t\t<helpsystem name="help">'
                                                 f'\n\t\t\t<fontPath>./{assets_folder_name}/fonts/TitilliumWeb-Black.ttf</fontPath>'
                                                 '\n\t\t\t<fontSize>0.020</fontSize>'
                                                 '\n\t\t\t<zIndex>5</zIndex>'
                                                 '\n\t\t</helpsystem>'
                                                 '\n\t\t<image name="BorderHelp" extra="true" ifHelpPrompts="true">'
                                                 f'\n\t\t\t<path>./{assets_folder_name}/overlays/borde_help.png</path>'
                                                 '\n\t\t\t<pos>0 0</pos>'
                                                 '\n\t\t\t<origin>0 0</origin>'
                                                 '\n\t\t\t<size>1 1</size>'
                                                 '\n\t\t\t<zIndex>4</zIndex>'
                                                 '\n\t\t</image>'
                                                 '\n\t</customView>'
                                                 '\n</theme>',
                     "vistas/menu.xml": '<?xml version="1.0" encoding="UTF-8"?>'
                                        '\n\n<theme>'
                                        '\n\t<formatVersion>7</formatVersion>'
                                        '\n\t<view name="menu">'
                                        '\n\t\t<menuText name="menutitle">'
                                        f'\n\t\t\t<fontPath>./{assets_folder_name}/fonts/flatwheat.ttf</fontPath>'
                                        '\n\t\t\t<fontSize>0.034</fontSize>'
                                        '\n\t\t\t<color>FAFAFA</color>'
                                        '\n\t\t</menuText>'
                                        '\n\n\t\t<menuText name="menufooter">'
                                        f'\n\t\t\t<fontPath>./{assets_folder_name}/fonts/Cabin-Regular.ttf</fontPath>'
                                        '\n\t\t\t<fontSize>0.02</fontSize>'
                                        '\n\t\t\t<color>777777FF</color>'
                                        '\n\t\t</menuText>'
                                        '\n\n\t\t<menuText name="menutext">'
                                        f'\n\t\t\t<fontPath>./{assets_folder_name}/fonts/ubuntu.ttf</fontPath>'
                                        '\n\t\t\t<fontSize>0.026</fontSize>'
                                        '\n\t\t\t<color>969696</color>'
                                        '\n\t\t\t<separatorColor>282828</separatorColor>'
                                        '\n\t\t\t<selectorColor>${baseColor}</selectorColor>'
                                        '\n\t\t\t<selectorColorEnd>${gradientEndColor}</selectorColorEnd>'
                                        '\n\t\t\t<selectedColor>FFFFFF</selectedColor>'
                                        '\n\t\t\t<selectorGradientType>horizontal</selectorGradientType>'
                                        '\n\t\t</menuText>'
                                        '\n\n\t\t<menuTextSmall name="menutextsmall">'
                                        f'\n\t\t\t<fontPath>./{assets_folder_name}/fonts/ubuntu.ttf</fontPath>'
                                        '\n\t\t\t<fontSize>0.016</fontSize>'
                                        '\n\t\t\t<color>${groupColor}</color>'
                                        '\n\t\t</menuTextSmall>'
                                        '\n\n\t\t<menuGroup name="menugroup">'
                                        f'\n\t\t\t<fontPath>./{assets_folder_name}/fonts/flatwheat.ttf</fontPath>'
                                        '\n\t\t\t<fontSize>0.018</fontSize>'
                                        '\n\t\t\t<color>${groupColor}</color>'
                                        '\n\t\t\t<separatorColor>${groupSeparatorColor}</separatorColor>'
                                        '\n\t\t\t<backgroundColor>00000000</backgroundColor>'
                                        '\n\t\t\t<lineSpacing>2.5</lineSpacing>'
                                        '\n\t\t</menuGroup>'
                                        '\n\n\t\t<menuBackground name="menubg">'
                                        '\n\t\t\t<color>242424</color>'
                                        '\n\t\t\t<cornerSize>32 32</cornerSize>'
                                        f'\n\t\t\t<path>./{assets_folder_name}/frame.png</path>'
                                        '\n\t\t\t<scrollbarColor>96969620</scrollbarColor>'
                                        '\n\t\t\t<scrollbarCorner>0.49</scrollbarCorner>'
                                        '\n\t\t\t<scrollbarSize>0.003</scrollbarSize>'
                                        '\n\t\t\t<scrollbarAlignment>innerright</scrollbarAlignment>'
                                        '\n\t\t</menuBackground>'
                                        '\n\n\t\t<menuIcons name="menuicons">'
                                        f'\n\t\t\t<iconKodi>./{assets_folder_name}/icons/Kodi.png</iconKodi>'
                                        f'\n\t\t\t<iconSystem>./{assets_folder_name}/icons/System.png</iconSystem>'
                                        f'\n\t\t\t<iconUpdates>./{assets_folder_name}/icons/Updates.png</iconUpdates>'
                                        f'\n\t\t\t<iconGames>./{assets_folder_name}/icons/Games.png</iconGames>'
                                        f'\n\t\t\t<iconControllers>./{assets_folder_name}/icons/Controllers.png</iconControllers>'
                                        f'\n\t\t\t<iconUI>./{assets_folder_name}/icons/UI.png</iconUI>'
                                        f'\n\t\t\t<iconSound>./{assets_folder_name}/icons/Sound.png</iconSound>'
                                        f'\n\t\t\t<iconNetwork>./{assets_folder_name}/icons/Network.png</iconNetwork>'
                                        f'\n\t\t\t<iconScraper>./{assets_folder_name}/icons/Scraper.png</iconScraper>'
                                        f'\n\t\t\t<iconAdvanced>./{assets_folder_name}/icons/Advanced.png</iconAdvanced>'
                                        f'\n\t\t\t<iconQuit>./{assets_folder_name}/icons/Quit.png</iconQuit>'
                                        f'\n\t\t\t<iconRestart>./{assets_folder_name}/icons/Restart.png</iconRestart>'
                                        f'\n\t\t\t<iconShutdown>./{assets_folder_name}/icons/Shutdown.png</iconShutdown>'
                                        f'\n\t\t\t<iconFastShutdown>./{assets_folder_name}/icons/Fastshutdown.png</iconFastShutdown>'
                                        f'\n\t\t\t<iconRetroachievements>./{assets_folder_name}/icons/Contest.png</iconRetroachievements>'
                                        f'\n\t\t\t<iconManual>./{assets_folder_name}/icons/Manual.png</iconManual>'
                                        '\n\t\t</menuIcons>'
                                        '\n\n\t\t<menuTextEdit name="menutextedit">'
                                        f'\n\t\t\t<inactive>./{assets_folder_name}/textinput_ninepatch.png</inactive>'
                                        f'\n\t\t\t<active>./{assets_folder_name}/textinput_ninepatch_active.png</active>'
                                        '\n\t\t</menuTextEdit>'
                                        '\n\t</view>'
                                        '\n</theme>',
                     "vistas/screen.xml": '<?xml version="1.0" encoding="UTF-8"?>'
                                          '\n\n<theme>'
                                          '\n\t<formatVersion>7</formatVersion>'
                                          '\n\t<view name="screen">'
                                          '\n\t\t<!-- Reloj -->'
                                          '\n\t\t<text name="clock">'
                                          '\n\t\t\t<visible>false</visible>'
                                          '\n\t\t</text>'
                                          '\n\t\t<!-- Indicador batería -->'
                                          '\n\t\t<batteryIndicator name="batteryIndicator">'
                                          '\n\t\t\t<visible>false</visible>'
                                          '\n\t\t</batteryIndicator>'
                                          '\n\t\t<!-- Indicador mandos -->'
                                          '\n\t\t<controllerActivity name="controllerActivity">'
                                          '\n\t\t\t<visible>false</visible>'
                                          '\n\t\t</controllerActivity>'
                                          '\n\t</view>'
                                          '\n</theme>',
                     "vistas/system.xml": '<?xml version="1.0" encoding="UTF-8"?>'
                                          '\n\n<theme>'
                                          '\n\t<formatVersion>7</formatVersion>'
                                          '\n\n\t<view name="system">'
                                          '\n\t\t<!-- Imagen / video de fondo -->'
                                          '\n\t\t<image name="background" extra="true">'
                                          '\n\t\t\t<size>1 1</size>'
                                          '\n\t\t\t<pos>0 0</pos>'
                                          f'\n\t\t\t<path>./{assets_folder_name}/bg.png</path>'
                                          '\n\t\t\t<zIndex>1</zIndex>'
                                          '\n\t\t</image>'
                                          '\n\n\t\t<!--<video name="staticBackgroundVideo" extra="true">'
                                          '\n\t\t\t<size>1 1</size>'
                                          '\n\t\t\t<pos>0 0</pos>'
                                          '\n\t\t\t<origin>0 0</origin>'
                                          f'\n\t\t\t<path>./{assets_folder_name}/videosystems/fondo.mp4</path>'
                                          '\n\t\t\t<zIndex>1</zIndex>'
                                          '\n\t\t</video>-->'
                                          '\n\n\t\t<!-- Logos sistemas -->'
                                          '\n\t\t<image name="logo">'
                                          f'\n\t\t\t<path>./{assets_folder_name}/logos/${{system.theme}}.png</path>'
                                          '\n\t\t</image>'
                                          '\n\n\t\t<!-- Logo de sistema en texto si falta imagen -->'
                                          '\n\t\t<text name="logoText">'
                                          f'\n\t\t\t<fontPath>./{assets_folder_name}/fonts/ubuntu.ttf</fontPath>'
                                          '\n\t\t\t<fontSize>0.04</fontSize>'
                                          '\n\t\t\t<color>FF8000</color>'
                                          '\n\t\t\t<forceUppercase>true</forceUppercase>'
                                          '\n\t\t</text>'
                                          '\n\n\t\t<!-- Menu de ayuda -->'
                                          '\n\t\t<helpsystem name="help">'
                                          f'\n\t\t\t<fontPath>./{assets_folder_name}/fonts/Watone.ttf</fontPath>'
                                          '\n\t\t</helpsystem>'
                                          '\n\t</view>'
                                          '\n</theme>',
                     "vistas/vista_sistemas/wheel_horizontal.xml": '<?xml version="1.0" encoding="UTF-8"?>'
                                                                   '\n\n<theme>'
                                                                   '\n\t<formatVersion>7</formatVersion>'
                                                                   '\n\n\t<view name="system">'
                                                                   '\n\t\t<!-- Modo de vista de los sistemas -->'
                                                                   '\n\t\t<carousel name="systemcarousel">'
                                                                   '\n\t\t\t<type>horizontal_wheel</type>'
                                                                   '\n\t\t\t<size>1 1</size>'
                                                                   '\n\t\t\t<pos>0.5 0.8</pos>'
                                                                   '\n\t\t\t<origin>0.5 0.5</origin>'
                                                                   '\n\t\t\t<gradientType>horizontal</gradientType>'
                                                                   '\n\t\t\t<logoScale>1.2</logoScale>'
                                                                   '\n\t\t\t<logoSize>0.18 0.18</logoSize>'
                                                                   '\n\t\t\t<logoRotation>9.5</logoRotation>'
                                                                   '\n\t\t\t<logoRotationOrigin>0.5 18</logoRotationOrigin>'
                                                                   '\n\t\t\t<logoAlignment>center</logoAlignment>'
                                                                   '\n\t\t\t<color>00000000</color>'
                                                                   '\n\t\t\t<colorEnd>00000000</colorEnd>'
                                                                   '\n\t\t\t<systemInfoDelay>700</systemInfoDelay>'
                                                                   '\n\t\t\t<systemInfoCountOnly>false</systemInfoCountOnly>'
                                                                   '\n\t\t\t<transitionSpeed>650</transitionSpeed>'
                                                                   '\n\t\t\t<minLogoOpacity>0.6</minLogoOpacity>'
                                                                   '\n\t\t\t<maxLogoCount>5</maxLogoCount>'
                                                                   '\n\t\t\t<defaultTransition>instant</defaultTransition>'
                                                                   '\n\t\t\t<zIndex>2</zIndex>'
                                                                   '\n\t\t\t<defaultTransition ifSubset="storyboards:yes">fade &amp; slide</defaultTransition>'
                                                                   '\n\t\t\t<itemTemplate ifSubset="storyboards:yes">'
                                                                   '\n\t\t\t\t<container>'
                                                                   '\n\t\t\t\t\t<image name="theLogoImage" pos="0.5" origin="0.5" maxSize="1" linearSmooth="true">'
                                                                   '\n\t\t\t\t\t\t<path>{system:logo}</path>'
                                                                   '\n\t\t\t\t\t</image>'
                                                                   '\n\t\t\t\t\t<!-- <storyboard event="activate">'
                                                                   '\n\t\t\t\t\t\t<animation property="opacity" to="1" duration="200" mode="Linear"/>'
                                                                   '\n\t\t\t\t\t</storyboard>'
                                                                   '\n\t\t\t\t\t<storyboard event="scroll">'
                                                                   '\n\t\t\t\t\t\t<animation property="opacity" to="0.6" duration="150" mode="Linear"/>'
                                                                   '\n\t\t\t\t\t\t<animation property="opacity" to="0" begin="1000" duration="250" mode="Linear"/>'
                                                                   '\n\t\t\t\t\t</storyboard>'
                                                                   '\n\t\t\t\t\t<storyboard event="deactivate">'
                                                                   '\n\t\t\t\t\t\t<animation property="opacity" to="0.6" duration="150" mode="Linear"/>'
                                                                   '\n\t\t\t\t\t\t<animation property="opacity" to="0" begin="1000" duration="250" mode="Linear"/>'
                                                                   '\n\t\t\t\t\t</storyboard> -->'
                                                                   '\n\t\t\t\t</container>'
                                                                   '\n\t\t\t</itemTemplate>'
                                                                   '\n\t\t</carousel>'
                                                                   '\n\n\t\t<!-- Numero de juegos del sistema -->'
                                                                   '\n\t\t<text name="systemInfo">'
                                                                   '\n\t\t\t<pos>0 0.8</pos>'
                                                                   '\n\t\t\t<size>1 0.25</size>'
                                                                   '\n\t\t\t<backgroundColor>00000000</backgroundColor>'
                                                                   '\n\t\t\t<color>${systemInfoColor}</color>'
                                                                   '\n\t\t\t<glowColor>${glowColor}</glowColor>'
                                                                   '\n\t\t\t<glowSize>2</glowSize>'
                                                                   '\n\t\t\t<!--<reflexion>0.50 0.10</reflexion>-->'
                                                                   f'\n\t\t\t<fontPath>./{assets_folder_name}/fonts/BusMatrix.ttf</fontPath>'
                                                                   '\n\t\t\t<fontSize>0.037</fontSize>'
                                                                   '\n\t\t\t<zIndex>5</zIndex>'
                                                                   '\n\t\t\t<storyboard ifSubset="storyboards:yes">'
                                                                   '\n\t\t\t\t<animation property="opacity" from="0" to="1" begin="1500" duration="100" mode="linear" repeat="1" autoReverse="true"/>'
                                                                   '\n\t\t\t\t<animation property="opacity" from="0" to="1" begin="1500" duration="300" mode="linear" repeat="1" autoReverse="true"/>'
                                                                   '\n\t\t\t\t<animation property="opacity" from="0" to="1" begin="1500" duration="500" mode="linear" repeat="1" autoReverse="true"/>'
                                                                   '\n\t\t\t\t<animation property="opacity" from="0" to="0.5" begin="1500" duration="750" mode="linear" repeat="1" autoReverse="true"/>'
                                                                   '\n\t\t\t\t<animation property="opacity" from="1" to="1" begin="1500" duration="1000" mode="linear" repeat="0" autoReverse="true"/>'
                                                                   '\n\t\t\t</storyboard>'
                                                                   '\n\t\t</text>'
                                                                   '\n\n\t\t<text name="systemInfoEx" extra="true">'
                                                                   '\n\t\t\t<text>Favoritos : {binding:favorites}</text>'
                                                                   '\n\t\t\t<verticalAlignment>center</verticalAlignment>'
                                                                   '\n\t\t\t<pos>0.468 0.9</pos>'
                                                                   '\n\t\t\t<size>0.3 0.14</size>'
                                                                   f'\n\t\t\t<fontPath>./{assets_folder_name}/fonts/BusMatrix.ttf</fontPath>'
                                                                   '\n\t\t\t<color>${systemInfoColor}</color>'
                                                                   '\n\t\t\t<alignment>left</alignment>'
                                                                   '\n\t\t\t<fontSize>0.025</fontSize>'
                                                                   '\n\t\t\t<zIndex>5</zIndex>'
                                                                   '\n\t\t\t<glowColor>${glowColor}</glowColor>'
                                                                   '\n\t\t\t<glowOffset>0.8</glowOffset>'
                                                                   '\n\t\t\t<glowSize>2</glowSize>'
                                                                   '\n\t\t</text>'
                                                                   '\n\n\t\t<image name="overlay" extra="true">'
                                                                   '\n\t\t\t<origin>0.5 0.5</origin>'
                                                                   '\n\t\t\t<pos>0.50 0.50</pos>'
                                                                   '\n\t\t\t<minSize>1 1</minSize>'
                                                                   '\n\t\t\t<color>ffffff</color>'
                                                                   f'\n\t\t\t<path>./{assets_folder_name}/overlays/overlay.png</path>'
                                                                   '\n\t\t\t<opacity>0.9</opacity>'
                                                                   '\n\t\t\t<zIndex>4</zIndex>'
                                                                   '\n\t\t</image>'
                                                                   '\n\n\t\t<!-- Menu de ayuda -->'
                                                                   '\n\t\t<helpsystem name="help">'
                                                                   '\n\t\t\t<pos>1 1</pos>'
                                                                   '\n\t\t</helpsystem>'
                                                                   '\n\t\t<image name="BorderHelp" extra="true" ifHelpPrompts="true">'
                                                                   '\n\t\t\t<visible>false</visible>'
                                                                   '\n\t\t</image>'
                                                                   '\n\t</view>'
                                                                   '\n</theme>',
                     "vistas/vista_sistemas/wheel.xml": '<?xml version="1.0" encoding="UTF-8"?>'
                                                        '\n\n<theme>'
                                                        '\n\t<formatVersion>7</formatVersion>'
                                                        '\n\n\t<view name="system">'
                                                        '\n\t\t<!-- Modo de vista de los sistemas -->'
                                                        '\n\t\t<carousel name="systemcarousel">'
                                                        '\n\t\t\t<type>vertical_wheel</type>'
                                                        '\n\t\t\t<pos>0.397 0</pos>'
                                                        '\n\t\t\t<size>1 1</size>'
                                                        '\n\t\t\t<origin>0 0</origin>'
                                                        '\n\t\t\t<color>FFFFFF00</color>'
                                                        '\n\t\t\t<logoScale>1.7</logoScale>'
                                                        '\n\t\t\t<logoSize>0.1 0.05</logoSize>'
                                                        '\n\t\t\t<logoRotation>7</logoRotation>'
                                                        '\n\t\t\t<logoRotationOrigin>5.5 0.5</logoRotationOrigin>'
                                                        '\n\t\t\t<logoAlignment>center</logoAlignment>'
                                                        '\n\t\t\t<maxLogoCount>5</maxLogoCount>'
                                                        '\n\t\t\t<defaultTransition>instant</defaultTransition>'
                                                        '\n\t\t\t<zIndex>2</zIndex>'
                                                        '\n\t\t</carousel>'
                                                        '\n\n\t\t<!-- Numero de juegos del sistema -->'
                                                        '\n\t\t<text name="systemInfo">'
                                                        '\n\t\t\t<pos>0 0.59</pos>'
                                                        '\n\t\t\t<size>1 0.25</size>'
                                                        '\n\t\t\t<backgroundColor>00000000</backgroundColor>'
                                                        '\n\t\t\t<color>${systemInfoColor}</color>'
                                                        '\n\t\t\t<glowColor>${glowColor}</glowColor>'
                                                        '\n\t\t\t<glowSize>2</glowSize>'
                                                        '\n\t\t\t<glowSize>1</glowSize>'
                                                        '\n\t\t\t<reflexion>0.20 0.0</reflexion>'
                                                        f'\n\t\t\t<fontPath>./{assets_folder_name}/fonts/BusMatrix.ttf</fontPath>'
                                                        '\n\t\t\t<fontSize>0.047</fontSize>'
                                                        '\n\t\t\t<zIndex>3</zIndex>'
                                                        '\n\t\t</text>'
                                                        '\n\n\t\t<!-- Menu de ayuda -->'
                                                        '\n\t\t<helpsystem name="help">'
                                                        '\n\t\t\t<pos>0.01 0.975</pos>'
                                                        '\n\t\t\t<fontSize>0.025</fontSize>'
                                                        '\n\t\t</helpsystem>'
                                                        '\n\t</view>'
                                                        '\n</theme>',
                     "vistas/vista_juegos/grid.xml": '<?xml version="1.0" encoding="UTF-8"?>'
                                                     '\n\n<theme>'
                                                     '\n\t<formatVersion>7</formatVersion>'
                                                     '\n\n\t<view name="grid">'
                                                     '\n\t\t<!-- Fondo de la vista -->'
                                                     '\n\t\t<image name="background">'
                                                     '\n\t\t\t<tile>false</tile>'
                                                     '\n\t\t\t<size>1 1</size>'
                                                     '\n\t\t\t<pos>0 0</pos>'
                                                     '\n\t\t\t<origin>0 0</origin>'
                                                     f'\n\t\t\t<path>./{assets_folder_name}/bg.png</path>'
                                                     '\n\t\t\t<color>${backgroundColor}</color>'
                                                     '\n\t\t\t<zIndex>1</zIndex>'
                                                     '\n\t\t</image>'
                                                     '\n\n\t\t<image name="systembg" extra="true">'
                                                     f'\n\t\t\t<path>./{assets_folder_name}/background/${{system.theme}}.jpg</path>'
                                                     '\n\t\t\t<linearSmooth>true</linearSmooth>'
                                                     '\n\t\t\t<pos>0.5 0.5</pos>'
                                                     '\n\t\t\t<minSize>1 1</minSize>'
                                                     '\n\t\t\t<origin>0.5 0.5</origin>'
                                                     '\n\t\t\t<color>FFFFFF15</color>'
                                                     '\n\t\t\t<zIndex>2</zIndex>'
                                                     '\n\t\t</image>'
                                                     '\n\n\t\t<!-- Logo sistema -->'
                                                     '\n\t\t<image name="logo" extra="false">'
                                                     f'\n\t\t\t<path>./{assets_folder_name}/logos/${{system.theme}}.svg</path>'
                                                     f'\n\t\t\t<path>./{assets_folder_name}/logos/${{system.theme}}.png</path>'
                                                     '\n\t\t\t<pos>0.5 0.074</pos>'
                                                     '\n\t\t\t<origin>0.5 0.5</origin>'
                                                     '\n\t\t\t<maxSize>0.26 0.11</maxSize>'
                                                     '\n\t\t\t<zIndex>500</zIndex>'
                                                     '\n\t\t</image>'
                                                     '\n\n\t\t<image name="linea-superior" extra="true">'
                                                     f'\n\t\t\t<path>./{assets_folder_name}/white.png</path>'
                                                     '\n\t\t\t<color>${baseColor}</color>'
                                                     '\n\t\t\t<origin>0 0</origin>'
                                                     '\n\t\t\t<pos>0 0.16</pos>'
                                                     '\n\t\t\t<size>1 0.005</size>'
                                                     '\n\t\t\t<zIndex>5</zIndex>'
                                                     '\n\t\t</image>'
                                                     '\n\n\t\t<!-- Cajas -->'
                                                     '\n\t\t<imagegrid name="gamegrid">'
                                                     '\n\t\t\t<margin>0.005 0.010</margin>'
                                                     '\n\t\t\t<pos>0.025 0.16</pos>'
                                                     '\n\t\t\t<size>0.950 0.84</size>'
                                                     '\n\t\t\t<padding>0.03 0.04 0.03 0.1</padding>'
                                                     '\n\t\t\t<autoLayout>6 2</autoLayout>'
                                                     '\n\t\t\t<autoLayout if="{system.theme} == \'snes\'">5 3</autoLayout>'
                                                     '\n\t\t\t<autoLayoutSelectedZoom>1.08</autoLayoutSelectedZoom>'
                                                     '\n\t\t\t<imageSizeMode>minSize</imageSizeMode>'
                                                     '\n\t\t\t<showVideoAtDelay>800</showVideoAtDelay>'
                                                     '\n\t\t\t<centerSelection>partial</centerSelection>'
                                                     '\n\t\t\t<animateSelection>false</animateSelection>'
                                                     '\n\t\t\t<centerSelection>false</centerSelection>'
                                                     '\n\t\t\t<scrollbarColor>96969620</scrollbarColor>'
                                                     '\n\t\t\t<scrollbarCorner>0.49</scrollbarCorner>'
                                                     '\n\t\t\t<scrollbarSize>0.005</scrollbarSize>'
                                                     '\n\t\t\t<zIndex>3</zIndex>'
                                                     '\n\t\t</imagegrid>'
                                                     '\n\n\t\t<!-- Fondo cuadrícula cajas -->'
                                                     '\n\t\t<gridtile name="default">'
                                                     '\n\t\t\t<backgroundColor>FFFFFF00</backgroundColor>'
                                                     '\n\t\t\t<backgroundCornerSize>9 9</backgroundCornerSize>'
                                                     '\n\t\t\t<selectionMode>image</selectionMode>'
                                                     '\n\t\t\t<padding>5 5</padding>'
                                                     '\n\t\t\t<imageColor>FFFFFFB0</imageColor>'
                                                     '\n\t\t</gridtile>'
                                                     '\n\n\t\t<!-- Recuadro selector juego (contorno) + "animación" color del mismo -->'
                                                     '\n\t\t<gridtile name="selected">'
                                                     '\n\t\t\t<backgroundCenterColor>${centerFadeColor}</backgroundCenterColor>'
                                                     '\n\t\t\t<backgroundEdgeColor>${bottomBarColor}</backgroundEdgeColor>'
                                                     '\n\t\t\t<imageColor>FFFFFFFF</imageColor>'
                                                     '\n\t\t</gridtile>'
                                                     '\n\n\t\t<!-- Evitar transparencia cajas y fusión con fondo -->'
                                                     '\n\t\t<image name="gridtile.image">'
                                                     '\n\t\t\t<linearSmooth>true</linearSmooth>'
                                                     '\n\t\t\t<shader>'
                                                     '\n\t\t\t\t<path>:/shaders/border.glsl</path>'
                                                     '\n\t\t\t\t<borderSize>0</borderSize>'
                                                     '\n\t\t\t\t<outerShadowSize>0</outerShadowSize>'
                                                     '\n\t\t\t\t<innerShadowSize>0</innerShadowSize>'
                                                     '\n\t\t\t\t<cornerRadius>0.016</cornerRadius>'
                                                     '\n\t\t\t</shader>'
                                                     '\n\t\t</image>'
                                                     '\n\n\t\t<ninepatch name="gridtile.background:selected">'
                                                     f'\n\t\t\t<path>./{assets_folder_name}/framewsel.png</path>'
                                                     '\n\t\t\t<animateColor>EFEF60B0</animateColor>'
                                                     '\n\t\t\t<animateColorTime>750</animateColorTime>'
                                                     '\n\t\t\t<cornerSize>36 36</cornerSize>'
                                                     '\n\t\t\t<padding>-18 -18</padding>'
                                                     '\n\t\t\t<color>${baseColor}</color>'
                                                     '\n\t\t</ninepatch>'
                                                     '\n\n\t\t<!-- Icono cuando NO es favorito -->'
                                                     '\n\t\t<image name="fav_no" extra="true">'
                                                     f'\n\t\t\t<path>./{assets_folder_name}/no.png</path>'
                                                     '\n\t\t\t<pos>-0.01 0.975</pos>'
                                                     '\n\t\t\t<size>0.04 0.025</size>'
                                                     '\n\t\t\t<zIndex>10</zIndex>'
                                                     '\n\t\t\t<visible>!{game:favorite}</visible>'
                                                     '\n\t\t</image>'
                                                     '\n\n\t\t<!-- Icono cuando SÍ es favorito -->'
                                                     '\n\t\t<image name="fav_yes" extra="true">'
                                                     f'\n\t\t\t<path>./{assets_folder_name}/yes.png</path>'
                                                     '\n\t\t\t<pos>-0.01 0.975</pos>'
                                                     '\n\t\t\t<size>0.04 0.025</size>'
                                                     '\n\t\t\t<zIndex>10</zIndex>'
                                                     '\n\t\t\t<visible>{game:favorite}</visible>'
                                                     '\n\t\t</image>'
                                                     '\n\n\t\t<text name="md_lbl_developer, md_lbl_publisher, md_lbl_lastplayed, md_lbl_playcount, md_lbl_players, md_lbl_releasedate, md_lbl_rating, md_playcount, md_lbl_genre">'
                                                     '\n\t\t\t<pos>2 2</pos>'
                                                     '\n\t\t</text>'
                                                     '\n\n\t\t<text name="md_genre, md_developer, md_publisher, md_players, md_description">'
                                                     '\n\t\t\t<pos>2 2</pos>'
                                                     '\n\t\t</text>'
                                                     '\n\n\t\t<datetime name="md_lastplayed, md_releasedate">'
                                                     '\n\t\t\t<pos>1 1</pos>'
                                                     '\n\t\t</datetime>'
                                                     '\n\n\t\t<image name="md_flag, md_kidgame, md_hidden, md_manual, md_fanart">'
                                                     '\n\t\t\t<pos>2 2</pos>'
                                                     '\n\t\t</image>'
                                                     '\n\n\t\t<rating name="md_rating">'
                                                     '\n\t\t\t<pos>2 2</pos>'
                                                     '\n\t\t</rating>'
                                                     '\n\n\t\t<helpsystem name="help">'
                                                     '\n\t\t\t<pos>2 2</pos>'
                                                     '\n\t\t</helpsystem>'
                                                     '\n\t</view>'
                                                     '\n</theme>',
                     "vistas/vista_juegos/detailed.xml": '<?xml version="1.0" encoding="UTF-8"?>'
                                                         '\n\n<theme>'
                                                         '\n\t<formatVersion>7</formatVersion>'
                                                         '\n\n\t<view name="detailed">'
                                                         '\n\t\t<textlist name="gamelist">'
                                                         '\n\t\t\t<lines>17</lines>'
                                                         '\n\t\t\t<primaryColor>C0C0C0</primaryColor>'
                                                         '\n\t\t\t<secondaryColor>F0F0F0</secondaryColor>'
                                                         '\n\t\t\t<selectorColor>${centerFadeColor}</selectorColor>'
                                                         '\n\t\t\t<selectedColor>FFFFFFFF</selectedColor>'
                                                         '\n\t\t\t<extraTextColor>606060</extraTextColor>'
                                                         '\n\t\t\t<!-- extraText color is for texts located between [] or () -->'
                                                         '\n\t\t\t<extraTextSelectedColor>A0A0A0</extraTextSelectedColor>'
                                                         '\n\t\t\t<forceUppercase>0</forceUppercase>'
                                                         '\n\t\t\t<pos>0.021 0.18</pos>'
                                                         '\n\t\t\t<size>0.489 0.73</size>'
                                                         '\n\t\t\t<zIndex>5</zIndex>'
                                                         '\n\t\t\t<alignment>left</alignment>'
                                                         '\n\t\t\t<horizontalMargin>0.00</horizontalMargin>'
                                                         f'\n\t\t\t<fontPath>./{assets_folder_name}/fonts/Cabin-Regular.ttf</fontPath>'
                                                         '\n\t\t\t<fontSize>0.028</fontSize>'
                                                         '\n\t\t\t<fontSize ifSubset="optimizesmallscreens:yes">0.0366</fontSize>'
                                                         f'\n\t\t\t<scrollSound>./{assets_folder_name}/sounds/scroll.wav</scrollSound>'
                                                         '\n\t\t\t<scrollbarColor>96969620</scrollbarColor>'
                                                         '\n\t\t\t<scrollbarCorner>0.49</scrollbarCorner>'
                                                         '\n\t\t\t<scrollbarSize>0.0065</scrollbarSize>'
                                                         '\n\t\t\t<scrollbarAlignment>outerright</scrollbarAlignment>'
                                                         '\n\t\t\t<horizontalMargin>0.005</horizontalMargin>'
                                                         '\n\t\t\t<glowColor>000000A0</glowColor>'
                                                         '\n\t\t\t<glowSize ifArch="windows,x86,x86_64,odroidc4,odroidxu4">1</glowSize>'
                                                         '\n\t\t</textlist>'
                                                         '\n\n\t\t<!-- Logo sistema -->'
                                                         '\n\t\t<image name="logo" extra="false">'
                                                         f'\n\t\t\t<path>./{assets_folder_name}/logos/${{system.theme}}.svg</path>'
                                                         f'\n\t\t\t<path>./{assets_folder_name}/logos/${{system.theme}}.png</path>'
                                                         '\n\t\t\t<pos>0.28 0.02</pos>'
                                                         '\n\t\t\t<pos if="{system.theme} == \'neogeo\'">0.28 -0.01</pos>'
                                                         '\n\t\t\t<size>0.25 0.13</size>'
                                                         '\n\t\t\t<size if="{system.theme} == \'neogeo\'">0.35 0.2</size>'
                                                         '\n\t\t\t<size if="{system.theme} == \'snes\' || {system.theme} == \'megadrive\'">0.35 0.13</size>'
                                                         '\n\t\t\t<zIndex>5</zIndex>'
                                                         '\n\t\t</image>'
                                                         '\n\n\t\t<video name="md_video">'
                                                         '\n\t\t\t<pos>0.76 0.408</pos>'
                                                         '\n\t\t\t<maxSize>0.46 0.436</maxSize>'
                                                         '\n\t\t\t<origin>0.5 0.5</origin>'
                                                         '\n\t\t\t<delay>0</delay>'
                                                         '\n\t\t\t<showSnapshotNoVideo>false</showSnapshotNoVideo>'
                                                         '\n\t\t\t<showSnapshotDelay>false</showSnapshotDelay>'
                                                         '\n\t\t\t<zIndex>3</zIndex>'
                                                         '\n\t\t\t<loops>0</loops>'
                                                         '\n\t\t\t<!--<roundCorners>0.02</roundCorners>-->'
                                                         '\n\t\t\t<effect>size</effect>'
                                                         '\n\t\t\t<shader>'
                                                         '\n\t\t\t\t<path>:/shaders/border.glsl</path>'
                                                         '\n\t\t\t\t<cornerRadius>0.03</cornerRadius>'
                                                         '\n\t\t\t\t<borderSize>0.014</borderSize>'
                                                         '\n\t\t\t\t<borderColor>${gradientEndColor}</borderColor>'
                                                         '\n\t\t\t\t<innerShadowSize>0.01</innerShadowSize>'
                                                         '\n\t\t\t\t<innerShadowColor>00000030</innerShadowColor>'
                                                         '\n\t\t\t\t<outerShadowSize>0.020</outerShadowSize>'
                                                         '\n\t\t\t\t<outerShadowColor>00000050</outerShadowColor>'
                                                         '\n\t\t\t</shader>'
                                                         '\n\t\t</video>'
                                                         '\n\n\t\t<image name="background">'
                                                         '\n\t\t\t<tile>false</tile>'
                                                         '\n\t\t\t<size>1 1</size>'
                                                         '\n\t\t\t<pos>0 0</pos>'
                                                         '\n\t\t\t<origin>0 0</origin>'
                                                         f'\n\t\t\t<path>./{assets_folder_name}/bg.png</path>'
                                                         '\n\t\t\t<color>${backgroundColor}</color>'
                                                         '\n\t\t\t<zIndex>1</zIndex>'
                                                         '\n\t\t</image>'
                                                         '\n\n\t\t<image name="systembg" extra="true">'
                                                         f'\n\t\t\t<path>./{assets_folder_name}/background/${{system.theme}}.jpg</path>'
                                                         '\n\t\t\t<linearSmooth>true</linearSmooth>'
                                                         '\n\t\t\t<pos>0.5 0.5</pos>'
                                                         '\n\t\t\t<minSize>1 1</minSize>'
                                                         '\n\t\t\t<origin>0.5 0.5</origin>'
                                                         '\n\t\t\t<color>FFFFFF15</color>'
                                                         '\n\t\t\t<zIndex>2</zIndex>'
                                                         '\n\t\t</image>'
                                                         '\n\n\t\t<image name="detailsBk" extra="true">'
                                                         f'\n\t\t\t<path>./{assets_folder_name}/overlays/filter.png</path>'
                                                         '\n\t\t\t<color>00000040</color>'
                                                         '\n\t\t\t<colorEnd>00000000</colorEnd>'
                                                         '\n\t\t\t<gradientType>horizontal</gradientType>'
                                                         '\n\t\t\t<origin>0 0</origin>'
                                                         '\n\t\t\t<pos>0.53 0.16</pos>'
                                                         '\n\t\t\t<size>0.4 0.774</size>'
                                                         '\n\t\t\t<zIndex>3</zIndex>'
                                                         '\n\t\t</image>'
                                                         '\n\n\t\t<image name="detailsBkLine" extra="true">'
                                                         f'\n\t\t\t<path>./{assets_folder_name}/white.png</path>'
                                                         '\n\t\t\t<color>${glowColor}</color>'
                                                         '\n\t\t\t<colorEnd>00000010</colorEnd>'
                                                         '\n\t\t\t<gradientType>horizontal</gradientType>'
                                                         '\n\t\t\t<origin>0 0</origin>'
                                                         '\n\t\t\t<pos>0.528 0.16</pos>'
                                                         '\n\t\t\t<size>0.003 0.775</size>'
                                                         '\n\t\t\t<size ifHelpPrompts="false">0.003 0.84</size>'
                                                         '\n\t\t\t<zIndex>3</zIndex>'
                                                         '\n\t\t</image>'
                                                         '\n\n\t\t<text name="md_lbl_developer, md_lbl_publisher, md_lbl_lastplayed, md_lbl_playcount, md_lbl_players, md_lbl_releasedate">'
                                                         '\n\t\t\t<color>969696</color>'
                                                         '\n\t\t\t<forceUppercase>0</forceUppercase>'
                                                         f'\n\t\t\t<fontPath>./{assets_folder_name}/fonts/Cabin-Regular.ttf</fontPath>'
                                                         '\n\t\t\t<fontSize>0.023</fontSize>'
                                                         '\n\t\t</text>'
                                                         '\n\n\t\t<text name="md_genre, md_developer, md_publisher, md_lastplayed, md_releasedate, md_players">'
                                                         '\n\t\t\t<color>969696</color>'
                                                         '\n\t\t\t<forceUppercase>0</forceUppercase>'
                                                         f'\n\t\t\t<fontPath>./{assets_folder_name}/fonts/Cabin-Bold.ttf</fontPath>'
                                                         '\n\t\t\t<fontSize>0.023</fontSize>'
                                                         '\n\t\t</text>'
                                                         '\n\n\t\t<text name="md_lbl_rating, md_lbl_publisher, md_publisher, md_lbl_lastplayed, md_lbl_playcount, md_playcount, md_lbl_releasedate, md_lbl_genre, md_lbl_developer">'
                                                         '\n\t\t\t<pos>1 1</pos>'
                                                         '\n\t\t</text>'
                                                         '\n\n\t\t<datetime name="md_lastplayed">'
                                                         '\n\t\t\t<pos>1 1</pos>'
                                                         '\n\t\t</datetime>'
                                                         '\n\n\t\t<image name="md_flag">'
                                                         '\n\t\t\t<origin>0 0.5</origin>'
                                                         '\n\t\t\t<pos>0.55 0.9</pos>'
                                                         '\n\t\t\t<maxSize>0.02 0.05</maxSize>'
                                                         '\n\t\t\t<zIndex>3</zIndex>'
                                                         '\n\t\t\t<linearSmooth>true</linearSmooth>'
                                                         '\n\t\t</image>'
                                                         '\n\n\t\t<text name="md_developer">'
                                                         '\n\t\t\t<color>EFEFFF</color>'
                                                         '\n\t\t\t<pos>0.578 0.875</pos>'
                                                         '\n\t\t\t<size>0.30 0.05</size>'
                                                         '\n\t\t\t<zIndex>3</zIndex>'
                                                         '\n\t\t\t<alignment>left</alignment>'
                                                         '\n\t\t\t<fontSize>0.025</fontSize>'
                                                         '\n\t\t</text>'
                                                         '\n\n\t\t<text name="md_genre">'
                                                         '\n\t\t\t<color>EFEFFF</color>'
                                                         '\n\t\t\t<pos>0.750 0.875</pos>'
                                                         '\n\t\t\t<size>0.30 0.05</size>'
                                                         '\n\t\t\t<zIndex>3</zIndex>'
                                                         '\n\t\t\t<alignment>left</alignment>'
                                                         '\n\t\t\t<fontSize>0.025</fontSize>'
                                                         '\n\t\t</text>'
                                                         '\n\n\t\t<rating name="md_rating">'
                                                         '\n\t\t\t<pos>0.94 0.886</pos>'
                                                         '\n\t\t\t<size>0.05 0.03</size>'
                                                         '\n\t\t\t<size verticalScreen="true">0.05 0.02</size>'
                                                         '\n\t\t\t<horizontalAlignment>right</horizontalAlignment>'
                                                         '\n\t\t\t<color>FFFF00</color>'
                                                         '\n\t\t\t<unfilledColor>808080</unfilledColor>'
                                                         '\n\t\t\t<unfilledPath>:/star_filled.svg</unfilledPath>'
                                                         '\n\t\t</rating>'
                                                         '\n\n\t\t<text name="md_lbl_players">'
                                                         '\n\t\t\t<pos>0.87 0.645</pos>'
                                                         '\n\t\t\t<pos verticalScreen="true">0.85 0.645</pos>'
                                                         '\n\t\t\t<size>0.09 0</size>'
                                                         '\n\t\t</text>'
                                                         '\n\n\t\t<text name="md_players">'
                                                         '\n\t\t\t<color>EFEFFF</color>'
                                                         '\n\t\t\t<pos>0.93 0.645</pos>'
                                                         '\n\t\t\t<size>0.05 0.033</size>'
                                                         '\n\t\t\t<zIndex>3</zIndex>'
                                                         '\n\t\t\t<alignment>right</alignment>'
                                                         '\n\t\t\t<singleLineScroll>true</singleLineScroll>'
                                                         '\n\t\t</text>'
                                                         '\n\n\t\t<text name="md_lbl_releasedate">'
                                                         '\n\t\t\t<color>969696</color>'
                                                         '\n\t\t\t<pos>0.55 0.645</pos>'
                                                         '\n\t\t\t<size>0.2 0</size>'
                                                         '\n\t\t</text>'
                                                         '\n\n\t\t<datetime name="md_releasedate">'
                                                         '\n\t\t\t<color>EFEFFF</color>'
                                                         '\n\t\t\t<pos>0.645 0.645</pos>'
                                                         '\n\t\t\t<pos verticalScreen="true">0.7 0.645</pos>'
                                                         '\n\t\t\t<size>0 0.033</size>'
                                                         '\n\t\t\t<format>${dateFormat}</format>'
                                                         '\n\t\t</datetime>'
                                                         '\n\n\t\t<text name="md_description">'
                                                         '\n\t\t\t<pos>0.55 0.7</pos>'
                                                         '\n\t\t\t<size>0.43 0.16</size>'
                                                         '\n\t\t\t<zIndex>3</zIndex>'
                                                         '\n\t\t\t<color>C0C0C0</color>'
                                                         '\n\t\t\t<forceUppercase>0</forceUppercase>'
                                                         f'\n\t\t\t<fontPath>./{assets_folder_name}/fonts/Cabin-Regular.ttf</fontPath>'
                                                         '\n\t\t\t<fontSize>0.023</fontSize>'
                                                         '\n\t\t\t<glowColor>000000A0</glowColor>'
                                                         '\n\t\t\t<glowSize ifArch="windows,x86,x86_64,odroidc4,odroidxu4">1</glowSize>'
                                                         '\n\t\t</text>'
                                                         '\n\n\t\t<image name="md_hidden">'
                                                         f'\n\t\t\t<path>./{assets_folder_name}/detailed/hidden.svg</path>'
                                                         '\n\t\t\t<pos>0.975 0.21</pos>'
                                                         '\n\t\t\t<maxSize>0.02 0.03</maxSize>'
                                                         '\n\t\t\t<origin>0.5 0.5</origin>'
                                                         '\n\t\t\t<color>969696</color>'
                                                         '\n\t\t\t<zIndex>15</zIndex>'
                                                         '\n\t\t</image>'
                                                         '\n\n\t\t<image name="md_kidgame">'
                                                         f'\n\t\t\t<path>./{assets_folder_name}/detailed/kid.svg</path>'
                                                         '\n\t\t\t<pos>0.86 0.9</pos>'
                                                         '\n\t\t\t<maxSize>0.02 0.03</maxSize>'
                                                         '\n\t\t\t<origin>0.5 0.5</origin>'
                                                         '\n\t\t\t<color>969696</color>'
                                                         '\n\t\t\t<zIndex>15</zIndex>'
                                                         '\n\t\t</image>'
                                                         '\n\n\t\t<image name="md_manual">'
                                                         f'\n\t\t\t<path>./{assets_folder_name}/detailed/manual.svg</path>'
                                                         '\n\t\t\t<pos>0.882 0.9</pos>'
                                                         '\n\t\t\t<maxSize>0.02 0.03</maxSize>'
                                                         '\n\t\t\t<origin>0.5 0.5</origin>'
                                                         '\n\t\t\t<color>969696</color>'
                                                         '\n\t\t\t<zIndex>15</zIndex>'
                                                         '\n\t\t</image>'
                                                         '\n\t</view>'
                                                         '\n</theme>',
                     "vistas/vista_juegos/gamecarousel.xml": '<?xml version="1.0" encoding="UTF-8"?>'
                                                             '\n\n<theme>'
                                                             '\n\t<formatVersion>7</formatVersion>'
                                                             '\n\n\t<view name="gamecarousel">'
                                                             '\n\t\t<gamecarousel name="gamecarousel">'
                                                             '\n\t\t\t<type>vertical_wheel</type>'
                                                             '\n\t\t\t<pos>0 0</pos>'
                                                             '\n\t\t\t<size>1 1</size>'
                                                             '\n\t\t\t<origin>0 0</origin>'
                                                             '\n\t\t\t<logoScale>1.4</logoScale>'
                                                             '\n\t\t\t<logoSize>0.14 0.14</logoSize>'
                                                             '\n\t\t\t<logoRotation>16</logoRotation>'
                                                             '\n\t\t\t<logoRotationOrigin>3.2 0.25</logoRotationOrigin>'
                                                             '\n\t\t\t<logoAlignment>right</logoAlignment>'
                                                             '\n\t\t\t<maxLogoCount>7</maxLogoCount>'
                                                             '\n\t\t\t<imageSource>marquee</imageSource> <!-- text, image, thumbnail, marquee -->'
                                                             f'\n\t\t\t<scrollSound>./{assets_folder_name}/sounds/scroll.wav</scrollSound>'
                                                             '\n\t\t\t<zIndex>3</zIndex>'
                                                             '\n\t\t</gamecarousel>'
                                                             '\n\n\t\t<helpsystem name="help">'
                                                             '\n\t\t\t<pos>1 1</pos>'
                                                             '\n\t\t</helpsystem>'
                                                             '\n\n\t\t<text name="gamecarouselLogoText">'
                                                             '\n\t\t\t<color>FFFFFFFF</color>'
                                                             '\n\t\t\t<glowColor>000000FF</glowColor>'
                                                             '\n\t\t\t<glowSize>4</glowSize>'
                                                             '\n\t\t\t<lineSpacing>1.0</lineSpacing>'
                                                             '\n\t\t</text>'
                                                             '\n\n\t\t<!-- Video scrapeado del juego -->'
                                                             '\n\t\t<video name="md_video">'
                                                             '\n\t\t\t<maxSize>0.33 0.46</maxSize>'
                                                             '\n\t\t\t<pos>0.199 0.4</pos>'
                                                             '\n\t\t\t<delay>0.8</delay>'
                                                             '\n\t\t\t<showSnapshotNoVideo>false</showSnapshotNoVideo>'
                                                             '\n\t\t\t<showSnapshotDelay>false</showSnapshotDelay>'
                                                             '\n\t\t\t<zIndex>2</zIndex>'
                                                             '\n\t\t</video>'
                                                             '\n\n\t\t<!-- Posicion y tamaño imagen juego -->'
                                                             '\n\t\t<image name="md_image">'
                                                             '\n\t\t\t<maxSize>0.35 0.4</maxSize>'
                                                             '\n\t\t\t<pos>0.2 0.4</pos>'
                                                             '\n\t\t\t<zIndex>2</zIndex>'
                                                             '\n\t\t</image>'
                                                             '\n\n\t\t<image name="background" extra="true">'
                                                             '\n\t\t\t<pos>0 0</pos>'
                                                             '\n\t\t\t<size>1 1</size>'
                                                             f'\n\t\t\t<path>./{assets_folder_name}/wheel.png</path>'
                                                             '\n\t\t\t<zIndex>1</zIndex>'
                                                             '\n\t\t</image>'
                                                             '\n\n\t\t<image name="logo">'
                                                             f'\n\t\t\t<path>./{assets_folder_name}/logos/${{system.theme}}.png</path>'
                                                             '\n\t\t\t<pos>0.51 0.02</pos>'
                                                             '\n\t\t\t<size>0.25 0.1</size>'
                                                             '\n\t\t\t<zIndex>1</zIndex>'
                                                             '\n\t\t</image>'
                                                             '\n\n\t\t<image name="md_fanart">'
                                                             '\n\t\t\t<pos>0.5 0</pos>'
                                                             '\n\t\t\t<size>0.5 1</size>'
                                                             '\n\t\t\t<origin>0 0</origin>'
                                                             '\n\t\t\t<color>FFFFFF00</color>'
                                                             '\n\t\t\t<colorEnd>FFFFFFB3</colorEnd>'
                                                             '\n\t\t\t<gradientType>horizontal</gradientType>'
                                                             '\n\t\t\t<linearSmooth>true</linearSmooth>'
                                                             '\n\t\t\t<zIndex>2</zIndex>'
                                                             '\n\t\t</image>'
                                                             '\n\n\t\t<text name="md_genre, md_developer, md_publisher, md_lastplayed, md_releasedate, md_players, md_lbl_developer, md_lbl_publisher, md_lbl_lastplayed, md_lbl_playcount, md_lbl_players, md_lbl_releasedate">'
                                                             '\n\t\t\t<storyboard>'
                                                             '\n\t\t\t\t<animation property="opacity" from="0" duration="350" mode="easeOut"/>'
                                                             '\n\t\t\t</storyboard>'
                                                             '\n\t\t</text>'
                                                             '\n\n\t\t<text name="md_lbl_developer, md_lbl_publisher, md_lbl_lastplayed, md_lbl_playcount, md_lbl_players, md_lbl_releasedate">'
                                                             '\n\t\t\t<color>969696</color>'
                                                             '\n\t\t\t<forceUppercase>0</forceUppercase>'
                                                             f'\n\t\t\t<fontPath>./{assets_folder_name}/fonts/ubuntu.ttf</fontPath>'
                                                             '\n\t\t\t<fontSize>0.023</fontSize>'
                                                             '\n\t\t</text>'
                                                             '\n\n\t\t<text name="md_genre, md_developer, md_publisher, md_lastplayed, md_releasedate, md_players">'
                                                             '\n\t\t\t<color>969696</color>'
                                                             '\n\t\t\t<forceUppercase>0</forceUppercase>'
                                                             f'\n\t\t\t<fontPath>./{assets_folder_name}/fonts/ubuntu.ttf</fontPath>'
                                                             '\n\t\t\t<fontSize>0.023</fontSize>'
                                                             '\n\t\t</text>'
                                                             '\n\n\t\t<text name="md_lbl_rating, md_lbl_publisher, md_publisher, md_lbl_lastplayed, md_lbl_playcount, md_playcount, md_lbl_releasedate, md_lbl_genre, md_lbl_developer">'
                                                             '\n\t\t\t<pos>1 1</pos>'
                                                             '\n\t\t</text>'
                                                             '\n\n\t\t<datetime name="md_lastplayed">'
                                                             '\n\t\t\t<pos>1 1</pos>'
                                                             '\n\t\t</datetime>'
                                                             '\n\n\t\t<image name="md_flag">'
                                                             '\n\t\t\t<origin>0 0.5</origin>'
                                                             '\n\t\t\t<pos>1 1</pos>'
                                                             '\n\t\t\t<maxSize>0.02 0.05</maxSize>'
                                                             '\n\t\t\t<linearSmooth>true</linearSmooth>'
                                                             '\n\t\t</image>'
                                                             '\n\n\t\t<text name="md_developer">'
                                                             '\n\t\t\t<color>EFEFFF</color>'
                                                             '\n\t\t\t<pos>1 1</pos>'
                                                             '\n\t\t\t<size>0.30 0.05</size>'
                                                             '\n\t\t\t<alignment>left</alignment>'
                                                             '\n\t\t\t<fontSize>0.025</fontSize>'
                                                             '\n\t\t</text>'
                                                             '\n\n\t\t<rating name="md_rating">'
                                                             '\n\t\t\t<pos>1 1</pos>'
                                                             '\n\t\t\t<size>0.05 0.03</size>'
                                                             '\n\t\t\t<size verticalScreen="true">0.05 0.02</size>'
                                                             '\n\t\t\t<horizontalAlignment>right</horizontalAlignment>'
                                                             '\n\t\t\t<color>FFFF00</color>'
                                                             '\n\t\t\t<unfilledColor>808080</unfilledColor>'
                                                             '\n\t\t\t<unfilledPath>:/star_filled.svg</unfilledPath>'
                                                             '\n\t\t</rating>'
                                                             '\n\n\t\t<text name="md_lbl_players">'
                                                             '\n\t\t\t<pos>1 1</pos>'
                                                             '\n\t\t\t<pos verticalScreen="true">0.85 0.645</pos>'
                                                             '\n\t\t\t<size>0.09 0</size>'
                                                             '\n\t\t</text>'
                                                             '\n\n\t\t<text name="md_players">'
                                                             '\n\t\t\t<color>EFEFFF</color>'
                                                             '\n\t\t\t<pos>1 1</pos>'
                                                             '\n\t\t\t<size>0.02 0</size>'
                                                             '\n\t\t</text>'
                                                             '\n\n\t\t<text name="md_lbl_releasedate">'
                                                             '\n\t\t\t<color>969696</color>'
                                                             '\n\t\t\t<pos>1 1</pos>'
                                                             '\n\t\t\t<size>0.2 0</size>'
                                                             '\n\t\t</text>'
                                                             '\n\n\t\t<datetime name="md_releasedate">'
                                                             '\n\t\t\t<color>EFEFFF</color>'
                                                             '\n\t\t\t<pos>1 1</pos>'
                                                             '\n\t\t\t<pos verticalScreen="true">0.7 0.645</pos>'
                                                             '\n\t\t\t<size>0 0.033</size>'
                                                             '\n\t\t\t<format>${dateFormat}</format>'
                                                             '\n\t\t</datetime>'
                                                             '\n\n\t\t<text name="md_description">'
                                                             '\n\t\t\t<color>00d2f3</color>'
                                                             '\n\t\t\t<pos>0.031 0.81</pos>'
                                                             '\n\t\t\t<size>0.46 0.15</size>'
                                                             f'\n\t\t\t<fontPath>./{assets_folder_name}/fonts/ubuntu.ttf</fontPath>'
                                                             '\n\t\t\t<fontSize>0.018</fontSize>'
                                                             '\n\t\t\t<forceUppercase>1</forceUppercase>'
                                                             '\n\t\t\t<zIndex>3</zIndex>'
                                                             '\n\t\t</text>'
                                                             '\n\n\t\t<image name="BorderHelp" extra="true" ifHelpPrompts="true">'
                                                             '\n\t\t\t<visible>false</visible>'
                                                             '\n\t\t</image>'
                                                             '\n\t</view>'
                                                             '\n</theme>'
                     }
    # -----------------------------------------------------------------
    # Definir contenido de cada archivo (rutas relativas a theme_folder)
    # Escribir cada archivo en su ruta dentro de theme_folder
    for rel_path, content in files_content.items():
        full_path = os.path.join(theme_folder, rel_path)
        _write_xml_file(full_path, content)

    # -----------------------------------------------------------------
    # 3. Assets básicos (carpetas y archivo de ejemplo)
    # -----------------------------------------------------------------
    # Crear subcarpetas típicas dentro de assets
    for subdir in ["fonts", "icons", "background", "logos", "overlays", "sounds"]:
        os.makedirs(os.path.join(assets_path, subdir), exist_ok=True)

    # Ruta a la carpeta assets del proyecto (origen)
    project_root = os.path.dirname(os.path.dirname(__file__))
    project_assets_dir = os.path.join(project_root, "assets")

    # Ruta destino de assets del nuevo tema
    dest_assets_dir = os.path.join(theme_folder, assets_folder_name)
    os.makedirs(dest_assets_dir, exist_ok=True)

    # Lista de elementos a copiar:
    # (origen_relativo, destino_relativo, es_carpeta)
    items_to_copy = [
        # ("carpeta_origen", "carpeta_destino", True), # Copia carpeta completa carpeta_origen -> carpeta_destino
        # ("logos/default.svg", "logos/default.svg", False), # Copia archivo carpeta_origen/nombre_archivo -> carpeta_destino/nombre_archivo
        ("bg.png", "bg.png", False),
        ("frame.png", "frame.png", False),
        ("framewsel.png", "framewsel.png", False),
        ("no.png", "no.png", False),
        ("wheel.png", "wheel.png", False),
        ("white.png", "white.png", False),
        ("yes.png", "yes.png", False),
        ("detailed", "detailed", True),  # carpeta completa detailed -> detailed
        ("menu_icons", "icons", True),  # carpeta completa iconos -> icons
        ("logos", "logos", True),  # carpeta completa logos -> logos
        ("overlays", "overlays", True),  # carpeta completa overlays -> overlays
        ("fuentes/BusMatrix.ttf", "fonts/BusMatrix.ttf", False),
        ("fuentes/Cabin-Bold.ttf", "fonts/Cabin-Bold.ttf", False),
        ("fuentes/Cabin-Regular.ttf", "fonts/Cabin-Regular.ttf", False),
        ("fuentes/flatwheat.ttf", "fonts/flatwheat.ttf", False),
        ("fuentes/TitilliumWeb-Black.ttf", "fonts/TitilliumWeb-Black.ttf", False),
        ("fuentes/ubuntu.ttf", "fonts/ubuntu.ttf", False),
        ("fuentes/Watone.ttf", "fonts/Watone.ttf", False),
        ("sonidos/scroll.wav", "sounds/scroll.wav", False),
        # Añade más según necesites:
    ]

    messages = copy_assets_from_template(project_assets_dir, dest_assets_dir, items_to_copy)

    # Crear un README informativo
    with open(os.path.join(theme_folder, "README.txt"), "w") as f:
        f.write(f"Coloca en la carpeta {assets_folder_name} tus imágenes, fuentes, etc.\n\n")
        f.write("Estructura sugerida:\n")
        f.write("  background/ - Fondos por sistema\n")
        f.write("  fonts/     - Fuentes .ttf .otf\n")
        f.write("  icons/     - Iconos para el menú\n")
        f.write("  logos/ - Logos de los sistemas\n")

    return messages


def copy_assets_from_template(project_assets_dir: str, dest_assets_dir: str, items: list) -> list:
    """
    Copia archivos o carpetas desde una plantilla de assets.
    Retorna una lista de mensajes de error/advertencia.
    """
    messages = []
    for src_rel, dst_rel, is_dir in items:
        src_path = os.path.join(project_assets_dir, src_rel)
        dst_path = os.path.join(dest_assets_dir, dst_rel)

        if not os.path.exists(src_path):
            messages.append(f"No existe el archivo: {src_rel}")
            continue

        os.makedirs(os.path.dirname(dst_path), exist_ok=True)

        try:
            if is_dir:
                if os.path.exists(dst_path):
                    shutil.rmtree(dst_path)
                shutil.copytree(src_path, dst_path)
            else:
                shutil.copy2(src_path, dst_path)
        except Exception as e:
            messages.append(f"Error copiando {src_rel}: {e}")
    return messages
